name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    # Run placeholder tests
    - name: Run Tests
      run: python3 manage.py test

    # Build and run Docker containers
    - name: Build and Deploy Docker Containers
      run: |
        docker compose down || true
        docker compose up --build -d
